agenda/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('', include('contatos.urls', namespace='contatos')),
    path('accounts/', include('users.urls', namespace='users')),
    path('admin/', admin.site.urls),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

contatos/urls.py
from django.urls import path
from .views import IndexView, Ver_ContatoView

app_name = 'contatos'

urlpatterns = [
    path('', IndexView.as_view(), name='index'),
    path('busca/', IndexView.as_view(), name='busca'),
    path('contato/<slug:slug>', Ver_ContatoView.as_view(), name='ver_contato'),
]

users/urls.py
from django.urls import path
from . import views

app_name = 'users'

urlpatterns = [
    path('', views.AccountsView.as_view(), name='accounts'),
    path('login/', views.login_view, name='login'),
    path('logout/', views.logout_view, name='logout'),
    path('cadastro/', views.register, name='cadastro'),
    path('dashboard/', views.dashboard, name='dashboard'),
]

contatos/models.py
from django.db import models
from django.utils import timezone


class Categoria(models.Model):
    nome = models.CharField(max_length=150)

    def __str__(self):
        return self.nome


class Contato(models.Model):
    nome = models.CharField(max_length=150, blank=False, null= False)
    sobrenome = models.CharField(max_length=150, blank=True)
    telefone = models.IntegerField(blank=False, null=False)
    email = models.EmailField(blank=True)
    data_criacao = models.DateTimeField(default=timezone.now)
    descricao = models.TextField(max_length=400, blank=True)
    categoria = models.ForeignKey(Categoria, on_delete=models.DO_NOTHING)
    mostrar = models.BooleanField(default=True)
    slug = models.SlugField(null=False)
    foto = models.ImageField(blank=True, upload_to='fotos/%Y/%m/%d')
    objetos = models.Manager()

    def __str__(self):
        return self.nome

users/models.py
from django.db import models

# Create your models here.

users/forms.py
from django import forms

from contatos.models import Contato


class FormContato(forms.ModelForm):
    class Meta:
        model = Contato
        exclude = ('mostrar',)

contatos/views.py
from django.shortcuts import get_object_or_404
from django.http import Http404
from .models import Contato
from django.views import generic
from django.db.models import Q, Value
from django.db.models.functions import Concat
from django.contrib import messages


class IndexView(generic.ListView):
    template_name = 'index.html'
    paginate_by = 2
    context_object_name = 'contatos'

    def get_queryset(self, **kwargs):
        termo = self.request.GET.get('termo')
        if termo is not None:
            if not termo:
                messages.add_message(
                    self.request,
                    messages.ERROR,
                    'Essa nao pode estar em branco',
                )
            else:
                messages.add_message(
                    self.request,
                    messages.SUCCESS,
                    'Enviado',
                )

        if termo:
            campos = Concat('nome', Value(' '), 'sobrenome')
            return Contato.objetos.annotate(nome_completo=campos).filter(
                Q(nome_completo__icontains=termo) | Q(id__icontains=termo)
                )

        return Contato.objetos.order_by('-id').filter(mostrar=True)


class Ver_ContatoView(generic.ListView):
    template_name = 'ver_contato.html'
    context_object_name = 'contato'

    def get_queryset(self, **kwargs):
        if self.kwargs:
            contato = get_object_or_404(Contato, slug=self.kwargs['slug'])
            if not contato.mostrar:
                raise Http404
            return contato

users/views.py
from django.contrib.auth.forms import UserCreationForm
from django.http import HttpResponseRedirect
from django.shortcuts import render
from django.views import generic
from django.contrib.auth import logout, login, authenticate
from django.urls import reverse
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from .forms import FormContato


class AccountsView(generic.TemplateView):
    template_name = 'accounts.html'


def login_view(request):
    if request.method != 'POST':
        return render(request, 'login.html')

    usuario = request.POST.get('usuario')
    senha = request.POST.get('senha')

    user = authenticate(username=usuario,
                        password=senha)
    if not user:
        messages.error(request, 'Usuario ou senha invalida.')
        return render(request, 'login.html')
    else:
        messages.success(request, 'Logado')
        login(request, user)
        return HttpResponseRedirect(reverse('users:dashboard'))


def logout_view(request):
        logout(request)
        return HttpResponseRedirect(reverse('users:accounts'))


def register(request):
    """Faz o cadastro de um novo usuario."""
    if request.method != 'POST':
        # Exibe o formulario de cadastro em branco
        form = UserCreationForm()
    else:
        # Processa o formulario preenchido
        form = UserCreationForm(data=request.POST)

        if form.is_valid():
            new_user = form.save()
            # Faz login do usuario e o redireciona para a pagina inicial
            authenticate_user = authenticate(username=new_user.username,
                                             password=request.POST['password1'])
            login(request, authenticate_user)
            messages.success(request, 'Cadastro enviado')
            return HttpResponseRedirect(reverse('users:login'))
    context = {'form': form}
    return render(request, 'cadastro.html', context)


@login_required(redirect_field_name='login')
def dashboard(request):
    if request.method != 'POST':
        form = FormContato()
    else:
        form = FormContato(request.POST, request.FILES)
        if form.is_valid():
            messages.success(request, f'Contato {request.POST.get("nome")} Salvo')
            form.save()
            return HttpResponseRedirect(reverse('users:dashboard'))

        else:
            messages.error(request, 'Erro ao enviar')
            form = FormContato(request.POST, request.FILES)
            context = {'form': form}
            return render(request, 'dashboard.html', context)

    context = {'form': form}
    return render(request, 'dashboard.html', context)

contatos/templates/contatos/_search.html
<br><br>
<form method="get" action="{% url 'contatos:busca' %}">
  <div class="form-group row">
    <div class="col-12">
      <input class="form-control"
             type="search" value="{{ request.GET.termo }}"
             id="search-input"
             placeholder="Digite sua pesquisa"
             name="termo">
    </div>
  </div>
</form>

contatos/templates/contatos/base.html
{% load bootstrap5 %}
<!DOCTYPE html>
<html lang="pt">

<head>
  <title>{% block titulo %}{% endblock %}Agenda</title>
  {% bootstrap_css %}
  {% bootstrap_javascript %}
  {% include '_head.html'%}
</head>

<body>
  {% include '_nav.html' %}

  <!-- Page Content -->
  <div class="container">
    <div class="row">
      <div class="col-lg-12">
        {% include '_messages.html' %}

        {% block conteudo %} {% endblock %}
      </div>
    </div>
  </div>

</body>

</html>

contatos/templates/contatos/index.html
{% extends 'base.html' %}

{% block conteudo %}
  {% include '_search.html' %}

<h1 class="mt-5">Minha agenda</h1>

<table class="table">
  <thead>
    <tr>
      <th>ID</th>
      <th>Nome</th>
      <th>Sobrenome</th>
      <th>Telefone</th>
      <th>Categoria</th>
      <th>Slug</th>
    </tr>
  </thead>
  <tbody>

    {% for contato in contatos %}

        <tr>
          <td>
            <a href="{% url 'contatos:ver_contato' contato.slug %}"> {{ contato.id }}</a>
          </td>
          <td>
            <a href="{% url 'contatos:ver_contato' contato.slug %}"> {{ contato.nome }}</a>
          </td>
          <td>{{ contato.sobrenome }}</td>
          <td>{{ contato.telefone }}</td>
          <td>{{ contato.categoria }}</td>
          <td>{{ contato.slug }}</td>
        </tr>

    {% endfor %}

  </tbody>
</table>

<nav aria-label="Page navigation example">
  <ul class="pagination">

    {% for pagina in page_obj.paginator.page_range %}
      {% if page_obj.number == pagina %}
        <li class="page-item active">
          <a class="page-link" href="?page={{ pagina }}&termo={{ request.GET.termo }}">{{ pagina }}</a>
        </li>
      {% else %}
        <li class="page-item">
          <a class="page-link" href="?page={{ pagina }}&termo={{ request.GET.termo }}">{{ pagina }}</a>
        </li>
      {% endif %}
    {% endfor%}

  </ul>
</nav>

{% endblock %}

contatos/templates/contatos/parciais/_head.html
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
<meta name="description" content="">
<meta name="author" content="">

<title>Agenda</title>

contatos/templates/contatos/parciais/_messages.html
{% load bootstrap5 %}
{% if messages %}
    {% for message in messages %}
        {% bootstrap_messages %}
    {% endfor %}
{% endif %}

contatos/templates/contatos/parciais/_nav.html
<!-- Navigation -->
<nav class="navbar navbar-expand-lg navbar-dark bg-dark static-top">
<div class="container">
  <a class="navbar-brand" href="{% url 'contatos:index' %}">Agenda</a>
  <a class="navbar-brand" href="{% url 'users:accounts' %}">Accounts</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarResponsive"
    aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
</div>
</nav>

contatos/templates/contatos/ver_contato.html
{% extends 'base.html' %}
{% block titulo %}{{ contato.nome }} {{ contato.sobrenome }} | {% endblock %}
{% block conteudo %}
<h1 class="mt-5">{{ contato.nome}} {{ contato.sobrenome }}</h1>
    <dl>

      {% if contato.foto %}
        <p>
          <img src="{{ contato.foto.url }}" style="max-width: 600px; height: auto;">
        </p>
      {% endif %}


      <dt>ID</dt>
      <dd>{{ contato.id }}</dd>

      <dt>Telefone</dt>
      <dd>{{ contato.telefone }}</dd>

      <dt>E-mail</dt>
      <dd>{{ contato.email }}</dd>

      <dt>Data criação</dt>
      <dd>{{ contato.data_criacao|date:'d/m/y' }}</dd>

      <dt>Categoria</dt>
      <dd>{{ contato.categoria }}</dd>

      <dt>Descrição</dt>
      <dd>
        {{ contato.descricao }}
      </dd>
    </dl>
{% endblock %}

users/templates/users/accounts.html
{% extends 'base.html' %}
{% block titulo %}Accounts | {% endblock %}
{% block conteudo %}
{% if user.is_authenticated %}
    <li><a>Olá, {{ user.username }}.</a></li>
    <li><a href="{% url 'users:logout' %}">logout</a></li>
    <li><a href="{% url 'users:dashboard' %}">Dashboard</a></li>
{% else %}
    <li><a href="{% url 'users:cadastro' %}">Cadastro</a></li>
    <li><a href="{% url 'users:login' %}">login</a></li>
{% endif%}
{% endblock %}

users/templates/users/cadastro.html
{% extends 'base.html' %}

{% block conteudo %}
{% block titulo %}Cadastro | {% endblock %}
{% if not user.is_authenticated %}
    <h1 class="mt-3, mb-3">Cadastro</h1>

    <form method="POST" action="{% url 'users:cadastro'%}">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit" class="btn btn-primary">Enviar</button>
        <input type="hidden" name="next" value="{% url 'users:login' %}" />
    </form>
{% else %}
    <li><a>Olá, {{ user.username }}. Voce já está cadastrado!</a></li>
    <li><a href="{% url 'users:logout' %}">logout</a></li>
    <li><a href="{% url 'users:dashboard' %}">Dashboard</a></li>
{% endif %}

{% endblock %}

users/templates/users/dashboard.html
{% extends 'base.html' %}
{% block titulo %}Dashboard de {{ user }} | {% endblock %}
{% block conteudo %}
    <h1>Dashboard</h1>
    <li><a>Olá, {{ user.username }}.</a></li>
    <li><a href="{% url 'users:logout' %}">logout</a></li>

    <div class="container">
        <form action="{% url 'users:dashboard' %}" method="post" enctype="multipart/form-data">
            {% csrf_token %}
            <table class="table">
                {{ form }}
            </table>
            <button name="submit" class="btn btn-primary">Enviar</button>

        </form>
    </div>
{% endblock %}

users/templates/users/login.html
{% extends 'base.html' %}
{% block titulo %}Login | {% endblock %}
{% block conteudo %}
{% if not user.is_authenticated %}
    <form method="POST" action="{% url 'users:login'%}">
        {% include '_messages.html' %}
        {% csrf_token %}
            <h1>Login</h1>
            <div class="form-group">
                <input type="text" name="usuario" value="{{request.POST.usuario}}"
                       class="form-control" placeholder="Usuario">
            </div>

            <div class="form-group">
                <input type="password" name="senha" class="form-control" placeholder="Senha">
            </div>

            <button type="submit" class="btn btn-primary">Enviar</button>
        </form>
{% else %}
    <li><a>Olá, {{ user.username }}. Voce já está logado!</a></li>
    <li><a href="{% url 'logout' %}">logout</a></li>
    <li><a href="{% url 'dashboard' %}">Dashboard</a></li>
{% endif %}

{% endblock %}